export const REMOVE_TAG = 'REMOVE_TAG'
export const ADD_TAG = 'ADD_TAG'
export const SEARCH_FILTER_PRODUCTS = "SEARCH_FILTER_PRODUCTS"
export const ADD_TO_CART = 'ADD_TO_CART'
export const TOGGLE_CART = 'TOGGLE_CART'
export const SUBMIT_FORM = 'SUBMIT_FORM'
export const ADJUST_QUANTITY = 'ADJUST_QUANTITY'